channels:
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - azureml-core==1.26.0
  - azureml-defaults==1.26.0
  - azureml-telemetry==1.26.0
  - azureml-train-restclients-hyperdrive==1.26.0
  - azureml-train-core==1.26.0
  - tensorflow-gpu==2.2.0
  - horovod==0.19.5
  - opencv-python
name: azureml_26be2a0bfcc81b6defa9235c1555b590
